### ISSUE TITLE
Add ability to specify debugging protocol

### ISSUE THREAD

**Issue by georgiy-abbasov** [romanresh/vscode-testcafe#11]
I've got this warning message when tried to run TestCafe tests on Node 8.0.0 Nightly:
`(node:9208) [DEP0062] DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.`
Application start arguments were:
`node --debug-brk=18621 --nolazy node_modules\testcafe\lib\cli\index.js chrome`

This message is shown, because latest Node.js builds are using "inspector" debugging protocol instead of "legacy", so we should set protocol (and debug arguments) automatically regards OS and Node.js version and\or have ability to set it.

https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_supported-nodelike-runtimes

**Comment by romanresh** [comment]
Wait for fix or answer on this report: https://github.com/Microsoft/vscode/issues/24762

**Comment by romanresh** [comment]
fixed in 1.4.0
