### ISSUE TITLE
Run test in loop

### ISSUE THREAD

**Issue by dennistruemperWork** [romanresh/vscode-testcafe#12]
![image](https://cloud.githubusercontent.com/assets/26621869/24804290/44527924-1bae-11e7-92f1-e545a7077cf9.png)

When I click in this test and ask to execute VS code tells this:
![image](https://cloud.githubusercontent.com/assets/26621869/24804348/711cfbaa-1bae-11e7-87e7-a682d97bb916.png)

However, run all tests in this file works fine.

**Comment by romanresh** [comment]
Hi @dennistruemperWork . As far as I know, TestCafe cannot run tests inside loops via **-t** and **-T** CLI parameters.

The VS Code extension only finds a test under a cursor position and passes its name to the TestCafe client. Its functionality is limited by features of TestCafe CLI (https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html)
