### ISSUE TITLE
Can't Run Individual Tests That Have Meta

### ISSUE THREAD

**Issue by dapperdandev** [romanresh/vscode-testcafe#24]
I right-click > Run Test(s) in chrome on individual tests quite frequently. I added meta to some of my tests which seems to prevent this extension from picking up the test name for the command output.

```javascript
test('this works', async t => {
    // running this test works fine
})

test.meta('key', 'value')('This does not work', async t => {
    // running this test actually runs the previous test.
})```

**Comment by romanresh** [comment]
Hi @djbreen7 . Just supported the meta() function in tests. Try v1.4.3 with the fix.  

Implemented in ab103d775e18779c6c0b84397d7bee4007810b01
