### ISSUE TITLE
Setup custom TestCafe command line arguments in config

### ISSUE THREAD

**Issue by romanresh** [romanresh/vscode-testcafe#3]

**Comment by douglastondo** [comment]
Hi, how can I setup arguments?

**Comment by romanresh** [comment]
Hi @douglastondo . There is no such feature in the current version. But I'm working on it.

**Comment by douglastondo** [comment]
Thank you @romanresh :)

**Comment by romanresh** [comment]
Ok, it's done. Use the new configuration key "testcafeTestRunner.customArguments" to pass any custom parameters to testcafe. See README.md.

**Comment by douglastondo** [comment]
Tested and it is working fine.
