### ISSUE TITLE
Improvement: Utilize Live Mode (Now Included In TestCafe)

### ISSUE THREAD

**Issue by dapperdandev** [romanresh/vscode-testcafe#30]
TestCafe Live is being absorbed into TestCafe as of TestCafe 1.0.0.

https://devexpress.github.io/testcafe/blog/testcafe-v1-0-0-released.html#live-mode-3215

How do you want to approach this? I imagine we'll want to add support for Live Mode for 1.0.0 users, but also maintain support for pre-1.0.0 users who still need to install testcafe-live separately. Thoughts?

**Comment by beeing** [comment]
Since VSCode supports installing older version, publishing the new features as new major version will be sufficient.

**Comment by romanresh** [comment]
Hi. I've just published v2.0.0 which changes behavior of the useLiveRunner option. It will add the --live argument to the testcafe if the option is enabled.

**Comment by dapperdandev** [comment]
@romanresh Sounds good. Thanks!
